apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: inventory-system
data:
  MONGO_URI: mongodb://mongo:27017/inventorydb
  ES_HOST: http://elasticsearch:9200
  ES_INDEX: products
